"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("./auth.controller");
const auth_types_1 = require("./auth.types");
const validation_middleware_1 = require("./validation.middleware");
const auth_middleware_1 = require("./auth.middleware");
const router = (0, express_1.Router)();
const authController = new auth_controller_1.AuthController();
router.post('/signup', (0, validation_middleware_1.validateBody)(auth_types_1.authenticateUserSchema), authController.signUp);
router.post('/signin', (0, validation_middleware_1.validateBody)(auth_types_1.authenticateUserSchema), authController.signIn);
router.post('/logout', auth_middleware_1.authenticateToken, authController.logout);
exports.default = router;
